### ISSUE TITLE
npm install error with dashing patch 2 on Ubuntu Bionic

### ISSUE THREAD

**Issue by asatria2** [RobotWebTools/ros2-web-bridge#127]
Hi,
Tried to follow the step on the readme and the build server log, but run into problem.

Any help will be much appreciated. Thanks!!
 
```console
user@pc:~/git/ros2-web-bridge$ ros2 run demo_nodes_cpp listener
[INFO] [listener]: I heard: [Hello World: 36]
[INFO] [listener]: I heard: [Hello World: 37]
[INFO] [listener]: I heard: [Hello World: 38]
^C[INFO] [rclcpp]: signal_handler(signal_value=2)
user@pc:~/git/ros2-web-bridge$ echo $AMENT_PREFIX_PATH
/home/user/ros2_install/ros2-linux
user@pc:~/git/ros2-web-bridge$ npm install --unsafe-perm 

> int64-napi@1.0.1 install /home/user/git/ros2-web-bridge/node_modules/int64-napi
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python3.6 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Linux 5.0.0-23-generic
gyp ERR! command "/home/user/git/nvm/versions/node/v10.16.2/bin/node" "/home/user/git/nvm/versions/node/v10.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/git/ros2-web-bridge/node_modules/int64-napi
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! int64-napi@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the int64-napi@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-08-15T08_11_47_878Z-debug.log
user@pc:~/git/ros2-web-bridge$ node -v
v10.16.2
user@pc:~/git/ros2-web-bridge$ npm -v
6.9.0
user@pc:~/git/ros2-web-bridge$ git branch
* (HEAD detached at 0.2.7)
  develop
user@pc:~/git/ros2-web-bridge$ 
```

**Comment by minggangw** [comment]
I think it doesn't happen any more, so let's close it.
