### ISSUE TITLE
Server stability bug -- unhandled underlying layer exceptions

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/ros2-web-bridge#8]
Case 1: Refresh browser as fast as you can, you'll hit this

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:949:11)
    at TCP.onread (net.js:563:26)
```

Case 2: connect to bridge with `service.html`, and then refresh.

```
   throw Error(`There is already service named ${serviceName}`);
    ^
Error: There is already service named /add_two_ints
    at Error (native)
```

**Comment by kenny-y** [comment]
Merging in more bugs and rename issue since they're similar -- exception handling.
